import { useState } from "react";
import { useNavigate } from "react-router-dom";
import {
  AlertDialog,
  AlertDialogAction,
  AlertDialogCancel,
  AlertDialogContent,
  AlertDialogDescription,
  AlertDialogFooter,
  AlertDialogHeader,
  AlertDialogTitle,
} from "@/components/ui/alert-dialog";
import { Loader2 } from "lucide-react";
import { supabase } from "@/integrations/supabase/client";
import { useAuth } from "@/contexts/AuthContext";
import { toast } from "sonner";
import type { Tables } from "@/integrations/supabase/types";

type CardData = Tables<"cards">;

interface DuplicateCardDialogProps {
  card: CardData;
  open: boolean;
  onOpenChange: (open: boolean) => void;
  onDuplicated?: () => void;
  /** Optional: target user ID for admin cross-user duplication */
  targetUserId?: string;
  /** Optional: target user name for display purposes */
  targetUserName?: string;
}

export function DuplicateCardDialog({
  card,
  open,
  onOpenChange,
  onDuplicated,
  targetUserId,
  targetUserName,
}: DuplicateCardDialogProps) {
  const navigate = useNavigate();
  const { user } = useAuth();
  const [duplicating, setDuplicating] = useState(false);

  // Determine if this is a cross-user duplication (admin flow)
  const isCrossUserDuplication = targetUserId && targetUserId !== card.user_id;
  const newOwnerId = targetUserId || user?.id;

  const handleDuplicate = async () => {
    if (!user || !newOwnerId) return;

    setDuplicating(true);
    try {
      // Generate new unique slug for the target user
      const slug = `${newOwnerId.slice(0, 8)}-${Date.now()}`;

      // FULL CARD DUPLICATION - copy ALL fields including personal data
      // Only change: user_id, slug, is_published, custom_slug, and reset counters
      const cardInsertData: any = {
        user_id: newOwnerId,
        slug,
        is_published: false, // New card starts unpublished
        views_count: 0,
        unique_views: 0,
        custom_slug: null, // Don't copy custom slug - must be unique
        // Copy ALL card fields exactly as they are
        theme: card.theme,
        carousel_enabled: card.carousel_enabled,
        cover_url: card.cover_url,
        logo_url: card.logo_url,
        // Personal data - copy everything
        full_name: isCrossUserDuplication 
          ? `${card.full_name}` // Keep original name for cross-user
          : `${card.full_name} (Copy)`, // Add suffix for same-user
        first_name: card.first_name,
        middle_name: card.middle_name,
        last_name: card.last_name,
        prefix: card.prefix,
        suffix: card.suffix,
        title: card.title,
        company: card.company,
        bio: card.bio,
        email: card.email,
        phone: card.phone,
        website: card.website,
        location: card.location,
        avatar_url: card.avatar_url,
        // QR and share URLs will be auto-generated by database triggers
        // or can be copied - either way is fine per requirements
        qr_code_url: null, // Will be regenerated
        vcard_url: null, // Will be regenerated
        wallet_pass_url: null,
        // Card type for limit enforcement
        card_type: 'transferable', // Duplicated cards are transferable by default
      };

      const { data: newCard, error: cardError } = await supabase
        .from("cards")
        .insert(cardInsertData)
        .select()
        .single();

      if (cardError) {
        // Check if it's a card limit error
        if (cardError.message?.includes('Card limit reached')) {
          toast.error("Card limit reached! Non-admin users can only have 2 cards. Please delete an existing card first.");
          return;
        }
        throw cardError;
      }

      // Copy product images (carousel) - ALWAYS copy for ALL users
      const { data: productImages, error: productImagesError } = await supabase
        .from("product_images")
        .select("*")
        .eq("card_id", card.id)
        .order("sort_order");

      if (productImagesError) {
        console.error("Error fetching product images:", productImagesError);
      }

      if (productImages && productImages.length > 0) {
        const productImageInserts = productImages.map((img, index) => ({
          card_id: newCard.id,
          owner: newOwnerId, // Set to new owner so RLS allows access
          image_url: img.image_url,
          alt_text: img.alt_text,
          description: img.description,
          sort_order: index,
        }));

        const { error: insertError } = await supabase
          .from("product_images")
          .insert(productImageInserts);
        
        if (insertError) {
          console.error("Error inserting product images:", insertError);
        }
      }

      // Copy card images (gallery) - ALWAYS copy for ALL users
      const { data: cardImages, error: cardImagesError } = await supabase
        .from("card_images")
        .select("*")
        .eq("card_id", card.id)
        .order("sort_index");

      if (cardImagesError) {
        console.error("Error fetching card images:", cardImagesError);
      }

      if (cardImages && cardImages.length > 0) {
        const cardImageInserts = cardImages.map((img) => ({
          card_id: newCard.id,
          url: img.url,
          sort_index: img.sort_index,
        }));

        const { error: insertError } = await supabase
          .from("card_images")
          .insert(cardImageInserts);
        
        if (insertError) {
          console.error("Error inserting card images:", insertError);
        }
      }

      // Copy card_links (social media, contact links) - ALWAYS copy for ALL users
      const { data: cardLinks, error: cardLinksError } = await supabase
        .from("card_links")
        .select("*")
        .eq("card_id", card.id)
        .order("sort_index");

      if (cardLinksError) {
        console.error("Error fetching card links:", cardLinksError);
      }

      if (cardLinks && cardLinks.length > 0) {
        const cardLinkInserts = cardLinks.map((link) => ({
          card_id: newCard.id,
          kind: link.kind,
          label: link.label,
          value: link.value,
          icon: link.icon,
          sort_index: link.sort_index,
        }));

        const { error: insertError } = await supabase
          .from("card_links")
          .insert(cardLinkInserts);
        
        if (insertError) {
          console.error("Error inserting card links:", insertError);
        }
      }

      if (isCrossUserDuplication) {
        toast.success(`Full card duplicated for ${targetUserName}!`);
      } else {
        toast.success("Card duplicated successfully!");
      }

      onOpenChange(false);
      onDuplicated?.();
      navigate(`/cards/${newCard.id}/edit`);
    } catch (error: any) {
      console.error("Error duplicating card:", error);
      if (error.message?.includes('Card limit reached')) {
        toast.error("Card limit reached! Non-admin users can only have 2 cards.");
      } else {
        toast.error("Failed to duplicate card");
      }
    } finally {
      setDuplicating(false);
    }
  };

  return (
    <AlertDialog open={open} onOpenChange={onOpenChange}>
      <AlertDialogContent>
        <AlertDialogHeader>
          <AlertDialogTitle>
            {isCrossUserDuplication
              ? `Duplicate Card for ${targetUserName}`
              : "Duplicate Card"}
          </AlertDialogTitle>
          <AlertDialogDescription>
            {isCrossUserDuplication ? (
              <>
                This will create a <strong>full copy</strong> of "{card.full_name}" for{" "}
                <strong>{targetUserName}</strong>. Everything will be copied:
                <ul className="mt-2 list-inside list-disc text-left">
                  <li>Theme, cover, logo, and avatar</li>
                  <li>All personal details (name, bio, contact info)</li>
                  <li>All social media links</li>
                  <li>All carousel/product images</li>
                  <li>All gallery images</li>
                </ul>
                <p className="mt-2 text-sm">
                  The new card will have a fresh URL and start as unpublished.
                </p>
              </>
            ) : (
              <>
                This will create a complete copy of "{card.full_name}" with all its design,
                content, images, and links. The new card will be unpublished and have a new
                unique URL.
              </>
            )}
          </AlertDialogDescription>
        </AlertDialogHeader>
        <AlertDialogFooter>
          <AlertDialogCancel disabled={duplicating}>Cancel</AlertDialogCancel>
          <AlertDialogAction onClick={handleDuplicate} disabled={duplicating}>
            {duplicating ? (
              <>
                <Loader2 className="mr-2 h-4 w-4 animate-spin" />
                Duplicating...
              </>
            ) : (
              "Duplicate Card"
            )}
          </AlertDialogAction>
        </AlertDialogFooter>
      </AlertDialogContent>
    </AlertDialog>
  );
}
