// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@0.20.0";

// src/lib/mcp/tools/search-cards.ts
import { defineTool } from "npm:@lovable.dev/mcp-js@0.20.0";
import { createClient } from "npm:@supabase/supabase-js@^2.81.1";
import { z } from "npm:zod@^3.23.8";
function client() {
  return createClient(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var search_cards_default = defineTool({
  name: "search_cards",
  title: "Search published cards",
  description: "Search Card-Ex published business cards by name, company, title, or bio. Returns basic public info.",
  inputSchema: {
    query: z.string().trim().min(1).describe("Text to match against name, company, title, or bio."),
    limit: z.number().int().min(1).max(50).optional().describe("Max results (default 10).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ query, limit }) => {
    const supabase = client();
    const pattern = `%${query}%`;
    const { data, error } = await supabase.from("cards").select("id, slug, custom_slug, full_name, title, company, bio, avatar_url").eq("is_published", true).or(
      `full_name.ilike.${pattern},company.ilike.${pattern},title.ilike.${pattern},bio.ilike.${pattern}`
    ).limit(limit ?? 10);
    if (error) {
      return { content: [{ type: "text", text: `Error: ${error.message}` }], isError: true };
    }
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? [], null, 2) }],
      structuredContent: { results: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/get-card.ts
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.20.0";
import { createClient as createClient2 } from "npm:@supabase/supabase-js@^2.81.1";
import { z as z2 } from "npm:zod@^3.23.8";
function client2() {
  return createClient2(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var get_card_default = defineTool2({
  name: "get_card",
  title: "Get a card by slug",
  description: "Fetch a published Card-Ex card by its slug or custom_slug. Returns public profile, contact, and social details.",
  inputSchema: {
    slug: z2.string().trim().min(1).describe("The card's slug or custom_slug (e.g. 'iameboybautista').")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ slug }) => {
    const supabase = client2();
    const { data, error } = await supabase.from("cards").select(
      "id, slug, custom_slug, full_name, title, company, bio, email, phone, location, avatar_url, cover_url, social_links, public_url, is_published"
    ).or(`slug.eq.${slug},custom_slug.eq.${slug}`).eq("is_published", true).maybeSingle();
    if (error) {
      return { content: [{ type: "text", text: `Error: ${error.message}` }], isError: true };
    }
    if (!data) {
      return { content: [{ type: "text", text: `No published card found for slug "${slug}".` }], isError: true };
    }
    return {
      content: [{ type: "text", text: JSON.stringify(data, null, 2) }],
      structuredContent: { card: data }
    };
  }
});

// src/lib/mcp/tools/list-recent-cards.ts
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.20.0";
import { createClient as createClient3 } from "npm:@supabase/supabase-js@^2.81.1";
import { z as z3 } from "npm:zod@^3.23.8";
function client3() {
  return createClient3(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var list_recent_cards_default = defineTool3({
  name: "list_recent_cards",
  title: "List recently published cards",
  description: "List the most recently published Card-Ex business cards.",
  inputSchema: {
    limit: z3.number().int().min(1).max(50).optional().describe("Max results (default 10).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ limit }) => {
    const supabase = client3();
    const { data, error } = await supabase.from("cards").select("id, slug, custom_slug, full_name, title, company, published_at").eq("is_published", true).order("published_at", { ascending: false, nullsFirst: false }).limit(limit ?? 10);
    if (error) {
      return { content: [{ type: "text", text: `Error: ${error.message}` }], isError: true };
    }
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? [], null, 2) }],
      structuredContent: { results: data ?? [] }
    };
  }
});

// src/lib/mcp/index.ts
var supabaseUrl = (process.env.SUPABASE_URL ?? "https://lorowpouhpjjxembvwyi.supabase.co").replace(/\/+$/, "");
var mcp_default = defineMcp({
  name: "card-ex-mcp",
  title: "Card-Ex by Tagex.app",
  version: "0.1.0",
  instructions: "Tools for discovering and reading public Card-Ex business cards on tagex.app. Use `search_cards` to find people or companies, `get_card` to fetch full details for a known slug, and `list_recent_cards` to browse recently published cards.",
  // Require a verified Supabase OAuth bearer token before any tool can run.
  auth: auth.oauth.issuer({
    issuer: `${supabaseUrl}/auth/v1`,
    acceptedAudiences: "authenticated",
    jwksUri: `${supabaseUrl}/auth/v1/.well-known/jwks.json`,
    resourceName: "Card-Ex MCP"
  }),
  tools: [search_cards_default, get_card_default, list_recent_cards_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.20.0/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
