// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://lorowpouhpjjxembvwyi.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imxvcm93cG91aHBqanhlbWJ2d3lpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjI2NzQ5MDAsImV4cCI6MjA3ODI1MDkwMH0.UNGqjitdE64q2Wm25yLTQsQCf2avGRdZC9IWy4fLIQ8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});